#ifndef __CONSTANT_H__
#define __CONSTANT_H__

enum {
    TAG_HERO_PHYS_BODY = 1<<0,
    TAG_BARRIER_PHYS_BODY = 1<<1,
    TAG_GROUND1_PHYS_BODY = 1<<2,
    TAG_GROUND2_PHYS_BODY = TAG_GROUND1_PHYS_BODY,
};

#endif
