#ifndef __CONSTANT_H__
#define __CONSTANT_H__

#define TAG_PHYS_BODY_HERO (1<<0)
#define TAG_PHYS_BODY_WALL (1<<1)
#define TAG_PHYS_BODY_BARRIER (1<<2)
#define TAG_PHYS_BODY_ENEMY (1<<3)
#define TAG_PHYS_BODY_GROUND (1<<4)
#define TAG_PHYS_BODY_CORD (1<<5)

#define BITMASK_PHYS_HERO TAG_PHYS_BODY_HERO
#define BITMASK_PHYS_WALL TAG_PHYS_BODY_WALL
#define BITMASK_PHYS_BARRIER TAG_PHYS_BODY_BARRIER
#define BITMASK_PHYS_ENEMY TAG_PHYS_BODY_ENEMY
#define BITMASK_PHYS_GROUND TAG_PHYS_BODY_GROUND
#define BITMASK_PHYS_CORD TAG_PHYS_BODY_CORD

#endif
