all:
	g++ -std=c++11 -DNDEBUG -O4 -Wall -o ELEEYE.EXE ../base/pipe.cpp ucci.cpp pregen.cpp position.cpp genmoves.cpp hash.cpp book.cpp movesort.cpp preeval.cpp evaluate.cpp search.cpp eleeye.cpp main.cpp -lpthread
