obj-y	+= \
	png.o \
	pngerror.o \
	pngget.o \
	pngmem.o \
	pngpread.o \
	pngread.o \
	pngrio.o \
	pngrtran.o \
	pngrutil.o \
	pngset.o \
	pngtrans.o

#obj-y	+= \
#	pngwio.o \
#	pngwrite.o \
#	pngwtran.o \
#	pngwutil.o
